name: Linux Conda CI

on:
    push:
    pull_request:

jobs:
    build:

        strategy:
            matrix:
                os: [ubuntu-22.04]
                python-version: ["3.10"]
            fail-fast: false

        runs-on: ${{ matrix.os }}

        name: ${{ matrix.os }} - ${{ matrix.python-version }}

        timeout-minutes: 90

        steps:

        - name: Configure system
          run: |
              sudo apt update
              sudo apt install mesa-common-dev libglu1-mesa-dev libgl1-mesa-glx libegl-dev

        - name: Checkout PCRaster
          uses: actions/checkout@v4

        - uses: conda-incubator/setup-miniconda@v3
          with:
              auto-update-conda: false
              python-version: ${{ matrix.python-version }}
              channels: conda-forge
              mamba-version: "*"
        - shell: bash -l {0}
          run: |
              mamba install boa -c conda-forge

        - name: Build
          shell: bash -l {0}
          run: |
              conda mambabuild environment/configuration/receipe --channel conda-forge --override-channels
